export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const EMAIL_PASSWORD_RESET = 'EMAIL_PASSWORD_RESET';
export const EMAIL_PASSWORD_RESET_SUCCESS = 'EMAIL_PASSWORD_RESER_SUCCESS';
export const EMAIL_PASSWORD_RESET_ERROR = 'EMAIL_PASSWORD_RESET_ERROR';

export const USERNAME_RESET = 'USERNAME_RESET';
export const USERNAME_RESET_SUCCESS = 'USERNAME_RESET_SUCCESS';
export const USERNAME_RESET_ERROR = 'USERNAME_RESET_ERROR';